import type { User, Cliente, Pedido, Vendedor, Product } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Patrão Admin",
    email: "patrao@empresa.com",
    role: "admin",
  },
  {
    id: "2",
    name: "Gerente Silva",
    email: "gerente@empresa.com",
    role: "Gerente",
  },
  {
    id: "3",
    name: "Yago Coordenador",
    email: "yago@empresa.com",
    role: "Coordenador",
  },
  {
    id: "4",
    name: "José Vendedor",
    email: "jose@empresa.com",
    role: "Vendedor",
  },
  {
    id: "5",
    name: "Maria Vendedora",
    email: "maria@empresa.com",
    role: "Vendedor",
  },
]

export const mockVendedores: Vendedor[] = [
  {
    id: "3",
    name: "Yago Coordenador",
    debitoTotal: 20000,
    carcacasPendentes: 12,
  },
  {
    id: "4",
    name: "José Vendedor",
    debitoTotal: 15000,
    carcacasPendentes: 8,
  },
  {
    id: "5",
    name: "Maria Vendedora",
    debitoTotal: 30000,
    carcacasPendentes: 15,
  },
]

export const mockClientes: Cliente[] = [
  {
    id: "c1",
    name: "Juninho Peças",
    vendedorId: "3",
    debitoTotal: 5000,
    carcacasPendentes: 3,
    ultimaAtualizacao: "2025-09-15",
  },
  {
    id: "c2",
    name: "Loja 2",
    vendedorId: "3",
    debitoTotal: 5000,
    carcacasPendentes: 2,
    ultimaAtualizacao: "2025-09-10",
  },
  {
    id: "c3",
    name: "Loja 3",
    vendedorId: "4",
    debitoTotal: 7000,
    carcacasPendentes: 5,
    ultimaAtualizacao: "2025-09-05",
  },
  {
    id: "c4",
    name: "Loja 4",
    vendedorId: "4",
    debitoTotal: 3000,
    carcacasPendentes: 1,
    ultimaAtualizacao: "2025-09-01",
  },
  {
    id: "c5",
    name: "Auto Peças Central",
    vendedorId: "5",
    debitoTotal: 12000,
    carcacasPendentes: 8,
    ultimaAtualizacao: "2025-09-20",
  },
  {
    id: "c6",
    name: "Mecânica do João",
    vendedorId: "5",
    debitoTotal: 8000,
    carcacasPendentes: 4,
    ultimaAtualizacao: "2025-09-18",
  },
]

export const mockPedidos: Pedido[] = [
  {
    id: "p1",
    numero: "PED-2025-0001",
    clienteId: "c1",
    vendedorId: "3",
    produto: "Embreagem Remanufaturada",
    tipoVenda: "base-troca",
    precoOriginal: 1000,
    desconto: 15,
    precoFinal: 850,
    debitoCarcaca: 150,
    statusCarcaca: "aguardando",
    dataCriacao: "2025-09-15",
    dataPrevisaoDevolucao: "2025-10-15",
  },
  {
    id: "p2",
    numero: "PED-2025-0002",
    clienteId: "c2",
    vendedorId: "3",
    produto: "Embreagem Nova",
    tipoVenda: "base-troca",
    precoOriginal: 1200,
    desconto: 12,
    precoFinal: 1056,
    debitoCarcaca: 144,
    statusCarcaca: "atrasado",
    dataCriacao: "2025-08-15",
    dataPrevisaoDevolucao: "2025-09-15",
  },
  {
    id: "p3",
    numero: "PED-2025-0003",
    clienteId: "c3",
    vendedorId: "4",
    produto: "Embreagem Remanufaturada",
    tipoVenda: "base-troca",
    precoOriginal: 1000,
    desconto: 10,
    precoFinal: 900,
    debitoCarcaca: 100,
    statusCarcaca: "aguardando",
    dataCriacao: "2025-09-25",
    dataPrevisaoDevolucao: "2025-10-25",
  },
  {
    id: "p4",
    numero: "PED-2025-0004",
    clienteId: "c4",
    vendedorId: "4",
    produto: "Embreagem Nova",
    tipoVenda: "normal",
    precoOriginal: 1200,
    desconto: 0,
    precoFinal: 1200,
    debitoCarcaca: 0,
    statusCarcaca: "devolvida",
    dataCriacao: "2025-09-01",
    dataPrevisaoDevolucao: "2025-09-01",
  },
  {
    id: "p5",
    numero: "PED-2025-0005",
    clienteId: "c5",
    vendedorId: "5",
    produto: "Embreagem Remanufaturada",
    tipoVenda: "base-troca",
    precoOriginal: 1000,
    desconto: 15,
    precoFinal: 850,
    debitoCarcaca: 150,
    statusCarcaca: "atrasado",
    dataCriacao: "2025-08-10",
    dataPrevisaoDevolucao: "2025-09-10",
  },
]

let pedidoCounter = 6

export function generatePedidoNumero(): string {
  const numero = `PED-2025-${String(pedidoCounter).padStart(4, "0")}`
  pedidoCounter++
  return numero
}

export const mockProducts: Product[] = [
  {
    id: "prod1",
    name: "Kit Embreagem Mercedes 1620",
    marca: "Mercedes",
    tipo: "Caminhões",
    categoria: "kit",
    precoBase: 1800,
    descontoMaximo: 15,
    ativo: true,
    dataCriacao: "2025-01-01",
  },
  {
    id: "prod2",
    name: "Platô Mercedes 1620",
    marca: "Mercedes",
    tipo: "Caminhões",
    categoria: "plato",
    precoBase: 800,
    descontoMaximo: 12,
    ativo: true,
    dataCriacao: "2025-01-01",
  },
  {
    id: "prod3",
    name: "Disco Mercedes 1620",
    marca: "Mercedes",
    tipo: "Caminhões",
    categoria: "disco",
    precoBase: 600,
    descontoMaximo: 10,
    ativo: true,
    dataCriacao: "2025-01-01",
  },
  {
    id: "prod4",
    name: "Mancal Mercedes 1620",
    marca: "Mercedes",
    tipo: "Caminhões",
    categoria: "mancal",
    precoBase: 400,
    descontoMaximo: 10,
    ativo: true,
    dataCriacao: "2025-01-01",
  },
  {
    id: "prod5",
    name: "Kit Embreagem Ford Cargo",
    marca: "Ford",
    tipo: "Caminhões",
    categoria: "kit",
    precoBase: 1700,
    descontoMaximo: 15,
    ativo: true,
    dataCriacao: "2025-01-15",
  },
  {
    id: "prod6",
    name: "Platô Volvo FH",
    marca: "Volvo",
    tipo: "Caminhões",
    categoria: "plato",
    precoBase: 900,
    descontoMaximo: 12,
    ativo: true,
    dataCriacao: "2025-02-01",
  },
  {
    id: "prod7",
    name: "Kit Embreagem Mercedes O500",
    marca: "Mercedes",
    tipo: "Ônibus",
    categoria: "kit",
    precoBase: 2000,
    descontoMaximo: 15,
    ativo: true,
    dataCriacao: "2025-02-15",
  },
]
